language: python
python:
 - "3.5"
 
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
install:
  - pip install requests

# command to run tests
script:
 - python -m unittest TestGithubInfo
